### ISSUE TITLE
Лучше бы в блок {} выделить if-body . 

### ISSUE THREAD

**Issue by DmitrTRC** [3rOFd/Work_2022_2#4]
https://github.com/3rOFd/Work_2022_2/blob/44d54104621a85df423728cd8c6008fcd731025b/Lecture_3_1/main.cpp#L12

* Старайся явно обрамлять каждый if/else
* Ну и в принципе  можно оттуда же сделать и return с ошибкой 1 - дабы вызывающий процесс понимал что не все Ок.

**Comment by 3rOFd** [comment]
Спасибо, учту)
