### ISSUE TITLE
Fix request

### ISSUE THREAD

**Issue by DmitrTRC** [3rOFd/Work_2022_2#8]
https://github.com/3rOFd/Work_2022_2/blob/2a1bfafb1291ff4d17c22a07d9acbc098e893be7/Lecture_3_5/main.cpp#L29

Смотри - ты проверял вообще на соответствие результата ?  Попробуй значение  0. 1 ( Просто проверь первые два члена ряда и сравни со своими )

Второе смотри - много повторяющегося кода. Тут DRY ( Do not Repeat Yourself   ) принцип рулит!  :)

**Comment by 3rOFd** [comment]
Сделал)
